# Generated by Django 3.2 on 2021-10-23 10:02

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome da empresa')),
                ('url', models.URLField(blank=True, max_length=155, verbose_name='Site da empresa')),
            ],
            options={
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to=core.models.project_image)),
                ('architects', models.CharField(max_length=255, verbose_name='Arquitectos')),
                ('area', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('tipology', models.CharField(choices=[('T0', 'T0'), ('T1', 'T1'), ('T1+1', 'T1+1'), ('T2', 'T2'), ('T2+1', 'T2+1'), ('T3', 'T3'), ('T3+1', 'T3+1'), ('T4', 'T4'), ('T4+1', 'T4+1'), ('T5', 'T5'), ('T5+1', 'T5+1')], default='T0', max_length=5)),
                ('photgraphs', models.CharField(max_length=255, verbose_name='Fotógrafos')),
                ('engineering', models.CharField(max_length=255, verbose_name='Engenheiros')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_background_image', models.ImageField(upload_to=core.models.settings_image)),
                ('admin_name', models.CharField(max_length=50, null=True, unique=True)),
                ('admin_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('admin_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format.', regex='^\\+?1?\\d{9,15}$')])),
                ('admin_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(verbose_name='Descrição do negócio')),
            ],
            options={
                'verbose_name_plural': 'Informações',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='core.Tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.project_image)),
                ('image_name', models.CharField(blank=True, max_length=150)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.projectsection')),
            ],
        ),
    ]
