# Generated by Django 3.2 on 2021-08-17 14:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_background_image', models.ImageField(upload_to=core.models.settings_image)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
