# Generated by Django 3.2 on 2021-11-06 17:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='main_background_image',
        ),
        migrations.AddField(
            model_name='project',
            name='construction',
            field=models.CharField(max_length=255, null=True, verbose_name='Construção'),
        ),
        migrations.AddField(
            model_name='project',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Destacar'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.CharField(max_length=255, null=True, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=20, null=True, verbose_name='Ano de construção'),
        ),
        migrations.AddField(
            model_name='settings',
            name='about_me_image',
            field=models.ImageField(null=True, upload_to=core.models.settings_image, verbose_name='Imagem "sobre mim"'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.Tag'),
        ),
    ]
