# Generated by Django 3.2 on 2021-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211106_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='admin_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='admin_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
