# Generated by Django 3.2 on 2021-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211106_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=255, null=True, verbose_name='Cliente'),
        ),
    ]
