# Generated by Django 3.2 on 2021-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210909_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do negócio')),
                ('services', models.CharField(max_length=255, verbose_name='Serviços')),
            ],
            options={
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome da empresa')),
                ('url', models.URLField(blank=True, max_length=155, verbose_name='Site da empresa')),
            ],
            options={
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Definições'},
        ),
    ]
