# Generated by Django 3.2 on 2021-11-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photgraphs',
            new_name='photographs',
        ),
    ]
