# Generated by Django 3.2 on 2021-11-12 23:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_photgraphs_project_photographs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.project_image),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='project',
            name='architects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arquitectos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='construction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Construção'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineering',
            field=models.CharField(blank=True, max_length=255, verbose_name='Engenheiros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fotógrafos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tipology',
            field=models.CharField(blank=True, default='T0', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano de construção'),
        ),
    ]
