# Generated by Django 3.2 on 2021-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210922_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='section_name',
            field=models.CharField(default='ola', max_length=150),
            preserve_default=False,
        ),
    ]
