# Generated by Django 3.2 on 2021-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descrição do negócio - English'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
