# Generated by Django 3.2 on 2021-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211115_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descrição - English'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Nome - English'),
        ),
    ]
