# Generated by Django 3.2 on 2021-12-20 16:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211117_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.settings_image),
        ),
    ]
